'use strict'
function createJavaTestTemplate(input) {
  const {key, skip, output, meta} = input
  return `// Generated by Java template
${output.hooks.deps.join('\n')}

public class ${key} extends ${meta.native ? 'NativeSetup' : 'TestSetup'} {
  ${output.hooks.vars.join('\n  ')}
  @BeforeMethod
  public void before(){
    ${output.hooks.beforeEach.join('\n    ')}
  }
  
  @AfterMethod
  public void after(){
    ${output.hooks.afterEach.join('\n    ')}
  }
  
  @Test${skip ? '(enabled=false)' : ''}
  public void ${key}() {
    ${output.commands.join('\n    ')}
  }
}`
}

module.exports = createJavaTestTemplate
