module.exports = [
    {name: 'TestCheckElementFully_Fluent', executionMode: {isVisualGrid: true}},
    {name: 'TestCheckElementFully_Fluent', executionMode: {isCssStitching: true}},
    {name: 'TestCheckElementFully_Fluent', executionMode: {isScrollStitching: true}},
    {
        name: 'TestCheckElementWithIgnoreRegionByElementOutsideTheViewport_Fluent',
        executionMode: {isVisualGrid: true},
    },
    {
        name: 'TestCheckElementWithIgnoreRegionByElementOutsideTheViewport_Fluent',
        executionMode: {isCssStitching: true},
    },
    {
        name: 'TestCheckElementWithIgnoreRegionByElementOutsideTheViewport_Fluent',
        executionMode: {isScrollStitching: true},
    },
    {
        name: 'TestCheckElementWithIgnoreRegionBySameElement_Fluent',
        executionMode: {isVisualGrid: true},
    },
    {
        name: 'TestCheckElementWithIgnoreRegionBySameElement_Fluent',
        executionMode: {isCssStitching: true},
    },
    {
        name: 'TestCheckElementWithIgnoreRegionBySameElement_Fluent',
        executionMode: {isScrollStitching: true},
    },
    {
        name: 'TestCheckFullWindowWithMultipleIgnoreRegionsBySelector_Fluent',
        executionMode: {isVisualGrid: true},
    },
    {
        name: 'TestCheckFullWindowWithMultipleIgnoreRegionsBySelector_Fluent',
        executionMode: {isCssStitching: true},
    },
    {
        name: 'TestCheckFullWindowWithMultipleIgnoreRegionsBySelector_Fluent',
        executionMode: {isScrollStitching: true},
    },
    {name: 'TestCheckOverflowingRegionByCoordinates_Fluent', executionMode: {isVisualGrid: true}},
    {
        name: 'TestCheckOverflowingRegionByCoordinates_Fluent',
        executionMode: {isCssStitching: true},
        disabled: true,
    },
    {
        name: 'TestCheckOverflowingRegionByCoordinates_Fluent',
        executionMode: {isScrollStitching: true},
        disabled: true,
    },
    {name: 'TestCheckPageWithHeader_Window', executionMode: {isVisualGrid: true}},
    {name: 'TestCheckPageWithHeader_Window', executionMode: {isCssStitching: true}},
    {name: 'TestCheckPageWithHeader_Window', executionMode: {isScrollStitching: true}},
    {name: 'TestCheckPageWithHeader_Window_Fully', executionMode: {isVisualGrid: true}},
    {name: 'TestCheckPageWithHeader_Window_Fully', executionMode: {isCssStitching: true}},
    {
        name: 'TestCheckPageWithHeader_Window_Fully',
        executionMode: {isScrollStitching: true},
        disabled: true,
    },
    {name: 'TestCheckPageWithHeader_Region', executionMode: {isVisualGrid: true}},
    {name: 'TestCheckPageWithHeader_Region', executionMode: {isCssStitching: true}},
    {name: 'TestCheckPageWithHeader_Region', executionMode: {isScrollStitching: true}},
    {name: 'TestCheckPageWithHeader_Region_Fully', executionMode: {isVisualGrid: true}},
    {
        name: 'TestCheckPageWithHeader_Region_Fully',
        executionMode: {isCssStitching: true},
        disabled: true,
    },
    {
        name: 'TestCheckPageWithHeader_Region_Fully',
        executionMode: {isScrollStitching: true},
        disabled: true,
    },
    {name: 'TestCheckRegion', executionMode: {isVisualGrid: true}},
    {name: 'TestCheckRegion', executionMode: {isCssStitching: true}},
    {name: 'TestCheckRegion', executionMode: {isScrollStitching: true}},
    {name: 'TestCheckRegion2', executionMode: {isVisualGrid: true}},
    {name: 'TestCheckRegion2', executionMode: {isCssStitching: true}},
    {name: 'TestCheckRegion2', executionMode: {isScrollStitching: true}},
    {name: 'TestCheckRegionByCoordinates_Fluent', executionMode: {isVisualGrid: true}},
    {name: 'TestCheckRegionByCoordinates_Fluent', executionMode: {isCssStitching: true}},
    {name: 'TestCheckRegionByCoordinates_Fluent', executionMode: {isScrollStitching: true}},
    {name: 'TestCheckRegionBySelectorAfterManualScroll_Fluent', executionMode: {isVisualGrid: true}},
    {
        name: 'TestCheckRegionBySelectorAfterManualScroll_Fluent',
        executionMode: {isCssStitching: true},
    },
    {
        name: 'TestCheckRegionBySelectorAfterManualScroll_Fluent',
        executionMode: {isScrollStitching: true},
        disabled: true,
    },
    {name: 'TestCheckRegionWithIgnoreRegion_Fluent', executionMode: {isVisualGrid: true}},
    {name: 'TestCheckRegionWithIgnoreRegion_Fluent', executionMode: {isCssStitching: true}},
    {name: 'TestCheckRegionWithIgnoreRegion_Fluent', executionMode: {isScrollStitching: true}},
    {name: 'TestCheckWindow', executionMode: {isVisualGrid: true}, disabled: true},
    {name: 'TestCheckWindow', executionMode: {isCssStitching: true}},
    {name: 'TestCheckWindow', executionMode: {isScrollStitching: true}},
    {name: 'TestCheckWindowAfterScroll', executionMode: {isVisualGrid: true}},
    {name: 'TestCheckWindowAfterScroll', executionMode: {isCssStitching: true}},
    {name: 'TestCheckWindowAfterScroll', executionMode: {isScrollStitching: true}},
    {name: 'TestCheckWindow_Body', executionMode: {isVisualGrid: true}},
    {name: 'TestCheckWindow_Body', executionMode: {isCssStitching: true}},
    {name: 'TestCheckWindow_Body', executionMode: {isScrollStitching: true}},
    {name: 'TestCheckWindow_Html', executionMode: {isVisualGrid: true}},
    {name: 'TestCheckWindow_Html', executionMode: {isCssStitching: true}},
    {name: 'TestCheckWindow_Html', executionMode: {isScrollStitching: true}},
    {name: 'TestCheckWindow_Fluent', executionMode: {isVisualGrid: true}, disabled: true},
    {name: 'TestCheckWindow_Fluent', executionMode: {isCssStitching: true}},
    {name: 'TestCheckWindow_Fluent', executionMode: {isScrollStitching: true}},
    {name: 'TestCheckWindowFully', executionMode: {isVisualGrid: true}},
    {name: 'TestCheckWindowFully', executionMode: {isCssStitching: true}},
    {name: 'TestCheckWindowFully', executionMode: {isScrollStitching: true}},
    {name: 'TestCheckWindowViewport', executionMode: {isVisualGrid: true}},
    {name: 'TestCheckWindowViewport', executionMode: {isCssStitching: true}},
    {name: 'TestCheckWindowViewport', executionMode: {isScrollStitching: true}},
    {name: 'TestCheckWindow_Simple_Html', executionMode: {isVisualGrid: true}},
    {name: 'TestCheckWindow_Simple_Html', executionMode: {isCssStitching: true}},
    {name: 'TestCheckWindow_Simple_Html', executionMode: {isScrollStitching: true}},
    {
        name: 'TestCheckWindowWithFloatingByRegion_Fluent',
        executionMode: {isVisualGrid: true},
        disabled: true,
    },
    {name: 'TestCheckWindowWithFloatingByRegion_Fluent', executionMode: {isCssStitching: true}},
    {name: 'TestCheckWindowWithFloatingByRegion_Fluent', executionMode: {isScrollStitching: true}},
    {
        name: 'TestCheckWindowWithFloatingBySelector_Fluent',
        executionMode: {isVisualGrid: true},
        disabled: true,
    },
    {name: 'TestCheckWindowWithFloatingBySelector_Fluent', executionMode: {isCssStitching: true}},
    {name: 'TestCheckWindowWithFloatingBySelector_Fluent', executionMode: {isScrollStitching: true}},
    {
        name: 'TestCheckWindowWithIgnoreBySelector_Fluent',
        executionMode: {isVisualGrid: true},
        disabled: true,
    },
    {name: 'TestCheckWindowWithIgnoreBySelector_Fluent', executionMode: {isCssStitching: true}},
    {name: 'TestCheckWindowWithIgnoreBySelector_Fluent', executionMode: {isScrollStitching: true}},
    {
        name: 'TestCheckWindowWithIgnoreBySelector_Centered_Fluent',
        executionMode: {isVisualGrid: true},
        disabled: true,
    },
    {
        name: 'TestCheckWindowWithIgnoreBySelector_Centered_Fluent',
        executionMode: {isCssStitching: true},
    },
    {
        name: 'TestCheckWindowWithIgnoreBySelector_Centered_Fluent',
        executionMode: {isScrollStitching: true},
    },
    {
        name: 'TestCheckWindowWithIgnoreBySelector_Stretched_Fluent',
        executionMode: {isVisualGrid: true},
        disabled: true,
    },
    {
        name: 'TestCheckWindowWithIgnoreBySelector_Stretched_Fluent',
        executionMode: {isCssStitching: true},
    },
    {
        name: 'TestCheckWindowWithIgnoreBySelector_Stretched_Fluent',
        executionMode: {isScrollStitching: true},
    },
    {name: 'TestDoubleCheckWindow', executionMode: {isVisualGrid: true}, disabled: true},
    {name: 'TestDoubleCheckWindow', executionMode: {isCssStitching: true}},
    {name: 'TestDoubleCheckWindow', executionMode: {isScrollStitching: true}},
    {name: 'TestSimpleRegion', executionMode: {isVisualGrid: true}},
    {name: 'TestSimpleRegion', executionMode: {isCssStitching: true}},
    {name: 'TestSimpleRegion', executionMode: {isScrollStitching: true}},
    {
        name: 'TestScrollbarsHiddenAndReturned_Fluent',
        executionMode: {isVisualGrid: true},
    },
    {
        name: 'TestScrollbarsHiddenAndReturned_Fluent',
        executionMode: {isCssStitching: true},
    },
    {
        name: 'TestScrollbarsHiddenAndReturned_Fluent',
        executionMode: {isScrollStitching: true},
    },
    {name: 'TestAbortIfNotClosed', executionMode: {isVisualGrid: true}},
    {name: 'TestAbortIfNotClosed', executionMode: {isCssStitching: true}},
    {name: 'TestCheckFixedRegion', executionMode: {isVisualGrid: true}},
    {name: 'TestCheckFixedRegion', executionMode: {isCssStitching: true}},
    {name: 'TestCheckFixedRegion', executionMode: {isScrollStitching: true}},
    {name: 'TestCheckFixedRegion_Fully', executionMode: {isVisualGrid: true}},
    {name: 'TestCheckFixedRegion_Fully', executionMode: {isCssStitching: true}},
    {name: 'TestCheckFixedRegion_Fully', executionMode: {isScrollStitching: true}},
    {name: 'TestSimpleModal', executionMode: {isVisualGrid: true}},
    {name: 'TestSimpleModal', executionMode: {isCssStitching: true}},
    {name: 'TestSimpleModal', executionMode: {isScrollStitching: true}},
    {name: 'TestScrollableModal_Fully', executionMode: {isCssStitching: true}},
    {name: 'TestScrollableModal_Fully', executionMode: {isScrollStitching: true}},
    {name: 'TestScrollableContentInModal_Fully', executionMode: {isCssStitching: true}},
    {name: 'TestScrollableContentInModal_Fully', executionMode: {isScrollStitching: true}},
    {name: 'TestWindowWithModal_Fully', executionMode: {isScrollStitching: true}},
]