'use strict'
function createTestFileString({key, skip, output, meta}) {
	return `//Generated by DotNet template
${output.hooks.deps.join('\n')}
  {
    ${output.hooks.vars.join('\n    ')}
 
    [SetUp]
    public void SetUpTest()
    {
    ${output.hooks.beforeEach.join('\n    ')}
    }
    
    [TearDown]
    public void TearDownTest()
    {
    ${output.hooks.afterEach.join('\n    ')}
    }

    [Test]
    [Category("Generated")] ${skip ? '\n    [Ignore("generated")]' : ''}
    public void ${key}()
    {
        ${output.commands.join('\n        ')}
    }
  }
}
`
}

module.exports = createTestFileString
