'use strict'
function createPytestTestFileString(emittedTest) {
    return `# Generated by Python template
${emittedTest.hooks.deps.join('\n')}

${emittedTest.hooks.vars.join('\n')}

${emittedTest.hooks.beforeEach.join('\n')}

${emittedTest.disabled ? '@pytest.mark.skip("generated")' : '' }
def ${emittedTest.name}(driver, eyes):
    ${emittedTest.commands.join('\n    ')}
`
}

module.exports = createPytestTestFileString
